// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAppgW0tWoKrWMW1XZUS1K3Da9jbRo-ibQ',
    appId: '1:10811891670:web:68bf0fff9b4e6b2bea0e77',
    messagingSenderId: '10811891670',
    projectId: 'mixmatch-73fc4',
    authDomain: 'mixmatch-73fc4.firebaseapp.com',
    storageBucket: 'mixmatch-73fc4.appspot.com',
    measurementId: 'G-01VNZGRC0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrADEX4C1tbJhjhOB2hTf6IKc6ZX_T0aQ',
    appId: '1:10811891670:android:ffcfbfeab70ab73bea0e77',
    messagingSenderId: '10811891670',
    projectId: 'mixmatch-73fc4',
    storageBucket: 'mixmatch-73fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08Yw6MeiUV9MvrjwnysEwH-hJXHQfLEA',
    appId: '1:10811891670:ios:a509e393bee9989dea0e77',
    messagingSenderId: '10811891670',
    projectId: 'mixmatch-73fc4',
    storageBucket: 'mixmatch-73fc4.appspot.com',
    iosBundleId: 'com.example.mixmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08Yw6MeiUV9MvrjwnysEwH-hJXHQfLEA',
    appId: '1:10811891670:ios:0d5c3b90bb64fb9eea0e77',
    messagingSenderId: '10811891670',
    projectId: 'mixmatch-73fc4',
    storageBucket: 'mixmatch-73fc4.appspot.com',
    iosBundleId: 'com.example.mixmatch.RunnerTests',
  );
}
